<template>
 <div class="page1">
   <LeftBar v-if="isShowLeftBar"></LeftBar>
   <div class="slide_box">
   	<Vslider :slides="slides"></Vslider>
   </div> 
   <div class="countDown">
     <h3>----距离过年还有----</h3>
     <VcountDown></VcountDown>
   </div>
   <div class="sale_show">
      <div class="img"><img src="../assets/sale.png"></div>
      <div class="sale_box">
        <div class="item" v-for="(i,index) in saleLists"  
        @mouseover="hoverThis=index"
        @mouseout="hoverThis=false"
        :class="[{cancelMargin:index==saleLists.length-1}]">
             <img :src="i.imgSrc" :class="{itemAnimate:index==hoverThis}" >
        </div>
      </div>
   </div>
   <div class="contanier verious">
     <div class="row" v-for="arr in chunkVeriousAll" >
       <div class="col-md-6 col-sm-6 verious_reponse" ><variousOf :pro="arr[0]"></variousOf></div>
       <div class="col-md-6 col-sm-6 verious_reponse" ><variousOf :pro="arr[1]" ></variousOf></div>
     </div>
   </div>
   <Category :datas="manDatas" id="vman"></Category>
   <Category :datas="womenDatas" id="vwomen"></Category>
   <Category :datas="interDatas" id="vinter"></Category>
 </div>	
</template>
<script type="text/javascript">
import Vslider from '../components/common/Vslider'
import VcountDown from '../components/common/countDown'
import VariousOf from '../components/common/variousOf'
import Category from '../components/category'
import LeftBar from '../components/leftBar'

export default{
  mounted(){
     $(window).scrollTop(0)
     $(window).on('scroll',()=>{
         if($(window).scrollTop()>300){
          this.isShowLeftBar=true
         }else{
          this.isShowLeftBar=false
         }
     })
  },
	data(){
		return{
          isShowLeftBar:false,
          hoverThis:false,
          isAnimate:false,
          slides:[
            {
              imgSrc:require('../assets/slide/1.jpg'),
              linkSrc:'' 
            },
            {
              imgSrc:require('../assets/slide/2.jpg'),
              linkSrc:'' 
            }
          ],
          saleLists:[
            {
              imgSrc:require("../assets/sale/1.jpg"),
              linkSrc:''
            },
            {
              imgSrc:require("../assets/sale/2.jpg"),
              linkSrc:''
            },
            {
              imgSrc:require("../assets/sale/3.jpg"),
              linkSrc:''
            }
          ],
          veriousAll:[
             {
              bgImg:require('../assets/verious/bg1.jpg'),
              logo:require("../assets/verious/1.png"),
              showList:[
                 {
                  imgSrc:require('../assets/verious/1.jpg'),
                  price:246,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:216,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:446,
                  linkSrc:''
                 }
              ],
              specialSrc:''
             },
             {
              bgImg:require('../assets/verious/bg1.jpg'),
              logo:require("../assets/verious/1.png"),
              showList:[
                 {
                  imgSrc:require('../assets/verious/1.jpg'),
                  price:246,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:216,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:446,
                  linkSrc:''
                 }
              ],
              specialSrc:''
             },
             {
              bgImg:require('../assets/verious/bg1.jpg'),
              logo:require("../assets/verious/1.png"),
              showList:[
                 {
                  imgSrc:require('../assets/verious/1.jpg'),
                  price:246,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:216,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:446,
                  linkSrc:''
                 }
              ],
              specialSrc:''
             },
             {
              bgImg:require('../assets/verious/bg1.jpg'),
              logo:require("../assets/verious/1.png"),
              showList:[
                 {
                  imgSrc:require('../assets/verious/1.jpg'),
                  price:246,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:216,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:446,
                  linkSrc:''
                 }
              ],
              specialSrc:''
             },
             {
              bgImg:require('../assets/verious/bg1.jpg'),
              logo:require("../assets/verious/1.png"),
              showList:[
                 {
                  imgSrc:require('../assets/verious/1.jpg'),
                  price:246,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:216,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:446,
                  linkSrc:''
                 }
              ],
              specialSrc:''
             },
             {
              bgImg:require('../assets/verious/bg1.jpg'),
              logo:require("../assets/verious/1.png"),
              showList:[
                 {
                  imgSrc:require('../assets/verious/1.jpg'),
                  price:246,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:216,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:446,
                  linkSrc:''
                 }
              ],
              specialSrc:''
             },
             {
              bgImg:require('../assets/verious/bg1.jpg'),
              logo:require("../assets/verious/1.png"),
              showList:[
                 {
                  imgSrc:require('../assets/verious/1.jpg'),
                  price:246,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:216,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:446,
                  linkSrc:''
                 }
              ],
              specialSrc:''
             },
             {
              bgImg:require('../assets/verious/bg1.jpg'),
              logo:require("../assets/verious/1.png"),
              showList:[
                 {
                  imgSrc:require('../assets/verious/1.jpg'),
                  price:246,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:216,
                  linkSrc:''
                 },
                 {
                  imgSrc:require('../assets/verious/2.jpg'),
                  price:446,
                  linkSrc:''
                 }
              ],
              specialSrc:''
             },
          ],
          manDatas:{
            tittle:"男装品牌",
            lists:[
              {
                srcImg:require("../assets/man/1.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/man/2.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/man/3.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/man/1.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/man/3.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/man/2.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
            ]
          },
          interDatas:{
            tittle:"国际品牌",
            lists:[
              {
                srcImg:require("../assets/inter/1.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"女装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/inter/2.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"女装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/inter/3.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"女装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/inter/1.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"女装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/inter/3.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"女装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/inter/2.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"女装专场",
                lastDay:1
              },
            ]
          },
          womenDatas:{
            tittle:"女装品牌",
            lists:[
              {
                srcImg:require("../assets/women/1.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/women/2.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/women/3.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/women/1.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/women/3.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
              {
                srcImg:require("../assets/women/2.jpg"),
                linkSrc:"",
                discount:0.5,
                fullDiscount:"满200减100，满10减8块",
                tittle:"爱马仕男装专场",
                lastDay:1
              },
            ]
          }
		}
	},
  metheds:{
    
  },
  computed:{
    chunkVeriousAll(){
     return  _.chunk(this.veriousAll,2)
    }
  },
	components:{
		Vslider,VcountDown,VariousOf,Category,LeftBar
	}
}	
</script>
<style type="text/css" >
.page1{max-width:1000px;width:100%;margin:0px auto;}
.slide_box{width:100%;box-sizing:border-box;border:20px solid #fff;border-radius:5px;}
.countDown{text-align: center;color:white;}
.sale_box{overflow:auto;width:100%;zoom:1;margin:15px 0px;}
.sale_box>.item{
  
  float:left;padding-right:3%;width:33.3%;
  box-sizing:border-box;max-height:105px;height:auto;
  overflow:hidden;
}
.sale_box>.item img{
  opacity:1;
}
.cancelMargin{padding-right:0px!important;}
.itemAnimate{
  animation: opacityMove 2s;
}
.verious{
  border-radius:10px;
  padding:10px;background:#fff;
}
@keyframes opacityMove{
  0%{opacity:0.5;}
  100%{opacity:1;}
}

</style>